# Generated by Django 5.1 on 2024-12-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=16)),
                ("password", models.CharField(max_length=16)),
                ("first_name", models.CharField(max_length=24)),
                ("middle_name", models.CharField(max_length=24)),
                ("last_name", models.CharField(max_length=24)),
                ("birthdate", models.DateField()),
                ("age", models.IntegerField()),
                ("position", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=11)),
            ],
        ),
    ]
