# Generated by Django 5.1 on 2024-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpensesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
