# Generated by Django 5.1 on 2024-12-22 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0002_expensescategory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
