# Generated by Django 5.1 on 2024-12-22 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0003_rename_users_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExpensesCategory",
            new_name="Category",
        ),
    ]
