# Generated by Django 5.1 on 2024-12-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0007_uploadfile_delete_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("ocr_results", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadFile",
        ),
    ]
