# Generated by Django 5.1 on 2024-12-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0008_ocr_delete_uploadfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocr",
            name="total_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ocr",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
