# Generated by Django 5.1 on 2024-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0009_ocr_total_value_alter_ocr_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocr",
            name="matched_store",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
