# Generated by Django 5.1 on 2024-12-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0010_ocr_matched_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocr",
            name="matched_store_category",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
