# Generated by Django 5.1 on 2024-12-24 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0012_remove_ocr_ocr_results"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ocr",
            new_name="Expense",
        ),
    ]
