# Generated by Django 5.1 on 2024-12-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0013_rename_ocr_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expensense.user",
            ),
        ),
    ]
