# Generated by Django 5.1 on 2024-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0015_user_updated_at_user_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="matched_store",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="matched_store_category",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
