# Generated by Django 5.1 on 2024-12-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0017_alter_expense_matched_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expensense.user",
            ),
        ),
    ]
