# Generated by Django 5.1 on 2024-12-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0018_alter_expense_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
