# Generated by Django 5.1 on 2024-12-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0019_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
