# Generated by Django 5.1 on 2025-01-03 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0027_user_is_active_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="AppUser",
        ),
    ]
