# Generated by Django 5.1 on 2025-01-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0028_rename_user_appuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="expense",
            name="uploaded_at",
            field=models.DateTimeField(),
        ),
    ]
