# Generated by Django 5.1 on 2025-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0030_appuser_is_active_appuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="uploaded_at",
            field=models.DateTimeField(),
        ),
    ]
