# Generated by Django 5.1 on 2025-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expensense", "0036_alter_expense_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="uploaded_at",
            field=models.DateTimeField(),
        ),
    ]
