# Generated by Django 5.1.5 on 2025-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0043_alter_expense_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
