# Generated by Django 5.1.5 on 2025-02-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0044_alter_expense_file_alter_expense_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='position',
        ),
    ]
