# Generated by Django 5.1.5 on 2025-02-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0045_remove_appuser_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_staff',
            new_name='guide1',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='is_superuser',
            new_name='guide2',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_login',
        ),
        migrations.AddField(
            model_name='appuser',
            name='guide3',
            field=models.BooleanField(default=False),
        ),
    ]
