# Generated by Django 5.1.5 on 2025-02-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0046_rename_is_staff_appuser_guide1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='guide1',
            new_name='guide_1',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='guide2',
            new_name='guide_2',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='guide3',
            new_name='guide_3',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
