# Generated by Django 5.1.5 on 2025-02-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0047_rename_guide1_appuser_guide_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
