# Generated by Django 5.1.5 on 2025-02-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0048_alter_appuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
