# Generated by Django 5.1.7 on 2025-03-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0049_alter_appuser_email_alter_appuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
