# Generated by Django 5.1.7 on 2025-03-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0050_alter_store_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
