# Generated by Django 5.1.7 on 2025-03-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0054_alter_expense_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=22),
        ),
    ]
