# Generated by Django 5.1.7 on 2025-03-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensense', '0058_alter_expense_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
